// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wordle.Data.Data.Contexts;

#nullable disable

namespace Wordle.Data.Data.Migrations
{
    [DbContext(typeof(WordleDbContext))]
    partial class WordleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Wordle.Data.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBeenPicked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastDatePicked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1228e521-f815-43cd-818a-6e1cc398351c"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3784),
                            Text = "apple"
                        },
                        new
                        {
                            Id = new Guid("7d307cd4-7119-487b-a3e8-f32b10db7894"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3833),
                            Text = "broke"
                        },
                        new
                        {
                            Id = new Guid("67dbac2c-f099-4323-8ac1-e21afc34add7"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3836),
                            Text = "chair"
                        },
                        new
                        {
                            Id = new Guid("3cbf7026-0410-4fdc-acae-b68ef1530030"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3838),
                            Text = "donut"
                        },
                        new
                        {
                            Id = new Guid("676ed03d-6da8-4031-a9bf-fa66968cb325"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3840),
                            Text = "elder"
                        },
                        new
                        {
                            Id = new Guid("443e2f67-1d94-4220-8b86-2c6d75960fc2"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3843),
                            Text = "found"
                        },
                        new
                        {
                            Id = new Guid("0ba179bc-26be-4cad-8604-4f011a85b91d"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3845),
                            Text = "ghoul"
                        },
                        new
                        {
                            Id = new Guid("1ec17595-ba0d-4c69-b2aa-e75fff9b1cb5"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3856),
                            Text = "harsh"
                        },
                        new
                        {
                            Id = new Guid("e9afa264-eb36-4e2d-baf9-7e57e00787f4"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3860),
                            Text = "index"
                        },
                        new
                        {
                            Id = new Guid("fc7f0ad0-d8ad-45d6-9fa4-b354396c13b6"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3863),
                            Text = "juice"
                        },
                        new
                        {
                            Id = new Guid("30b1f7bb-0dc1-4f9a-b320-d94dda6a85ad"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3867),
                            Text = "karma"
                        },
                        new
                        {
                            Id = new Guid("69b5932a-125d-4188-932d-1ffb4e58c60f"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3870),
                            Text = "liver"
                        },
                        new
                        {
                            Id = new Guid("28bd30d5-0016-4c19-9af1-88997622ca1a"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3873),
                            Text = "mount"
                        },
                        new
                        {
                            Id = new Guid("a8481094-220b-48d8-9dac-e6d9c1b09613"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3876),
                            Text = "novel"
                        },
                        new
                        {
                            Id = new Guid("5463f1a9-733c-420e-aa9e-e4bf072cc6de"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3879),
                            Text = "offer"
                        },
                        new
                        {
                            Id = new Guid("562d7821-7ba3-41c0-bf9a-4e2bb0881aa6"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3885),
                            Text = "query"
                        },
                        new
                        {
                            Id = new Guid("71466e99-596e-4689-aae2-e0df31790ce9"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3890),
                            Text = "round"
                        },
                        new
                        {
                            Id = new Guid("152ea109-3d47-4358-87de-d48bc14cd980"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3893),
                            Text = "south"
                        },
                        new
                        {
                            Id = new Guid("07e17255-0597-4d9c-ae09-d192899dd58a"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3897),
                            Text = "timer"
                        },
                        new
                        {
                            Id = new Guid("3e14ee02-0787-455b-8bb1-6e292f982bb5"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3899),
                            Text = "under"
                        },
                        new
                        {
                            Id = new Guid("d4551233-bb8f-4ad9-aa7e-2a14b813b148"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3901),
                            Text = "vocal"
                        },
                        new
                        {
                            Id = new Guid("fde410f9-b8b7-46ca-858f-b6cf0556d12a"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3903),
                            Text = "worth"
                        },
                        new
                        {
                            Id = new Guid("58cd89c0-e343-4740-b96b-996a87e8e02c"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3906),
                            Text = "xerox"
                        },
                        new
                        {
                            Id = new Guid("d32ec034-96b5-4baf-af43-04eb94c861db"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3911),
                            Text = "yield"
                        },
                        new
                        {
                            Id = new Guid("f17fb8cc-e702-4308-81a9-4b3fb50fb878"),
                            HasBeenPicked = false,
                            LastDatePicked = new DateTime(2024, 10, 25, 16, 20, 51, 752, DateTimeKind.Local).AddTicks(3913),
                            Text = "zebra"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
